#requires -Version 7.4
<#
Validate the versioned policy and render the project Codex configuration.
Run without arguments to check for drift; -Write updates only the owned output.
PowerShell 7.4+ is available on Windows, macOS, and Linux; no modules are required.
#>
[CmdletBinding()]
param([switch]$Write)

$ErrorActionPreference = 'Stop'
$projectRoot = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '../..'))
$policyPath = Join-Path $projectRoot 'config/ai/agent-policy.json'
$schemaPath = Join-Path $projectRoot 'schemas/ai/agent-policy.v3.schema.json'
$outputPath = Join-Path $projectRoot '.codex/config.toml'
$marker = '# Generated by tools/ai/sync-config.ps1; edit config/ai/agent-policy.json.'

$policyText = Get-Content -LiteralPath $policyPath -Raw
if (-not (Test-Json -Json $policyText -SchemaFile $schemaPath)) {
    throw 'Agent policy does not match its versioned schema.'
}
$policy = $policyText | ConvertFrom-Json
# Schema validation restricts all interpolated values to safe TOML scalar values.
$lines = @(
    $marker
    '# Project defaults; explicit session settings may override these values.'
    "model = `"$($policy.model)`""
    "model_reasoning_effort = `"$($policy.model_reasoning_effort)`""
    "model_verbosity = `"$($policy.model_verbosity)`""
    "tool_output_token_limit = $($policy.tool_output_token_limit)"
    ''
    '# The concurrency limit counts subagents only; add one for the coordinator.'
    '[agents]'
    "enabled = $($policy.agents.enabled.ToString().ToLowerInvariant())"
    "max_concurrent_threads_per_session = $($policy.agents.max_concurrent_threads_per_session)"
    "default_subagent_model = `"$($policy.agents.default_subagent_model)`""
    "default_subagent_reasoning_effort = `"$($policy.agents.default_subagent_reasoning_effort)`""
)
$expected = ($lines -join "`n") + "`n"
$existing = if (Test-Path -LiteralPath $outputPath) {
    [IO.File]::ReadAllText($outputPath).Replace("`r`n", "`n")
} else { $null }

if ($existing -ceq $expected) {
    Write-Output 'PASS: schema valid; Codex configuration matches policy.'
    exit 0
}
if (-not $Write) { throw 'Configuration missing or stale. Run tools/ai/sync-config.ps1 -Write.' }
if ($null -ne $existing -and -not $existing.StartsWith($marker)) {
    throw 'Existing Codex config is not owned by this generator. Reconcile it before writing.'
}
[IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($outputPath)) | Out-Null
[IO.File]::WriteAllText($outputPath, $expected, [Text.UTF8Encoding]::new($false))
Write-Output 'PASS: schema valid; wrote .codex/config.toml.'
