#nullable enable
using UnityEngine;

namespace Elts.Operator
{
    /// <summary>Ownership marker for children regenerated by the desktop scene authoring command.</summary>
    [DisallowMultipleComponent]
    public sealed class DevelopmentEnvironmentGenerated : MonoBehaviour { }
}
